/* Black Tilt Hydrometer iBeacon decode (advertising-only).
 * This code is generated by AI using the following reference:
 *   https://kvurd.com/blog/tilt-hydrometer-ibeacon-data-format/
 */
#pragma once
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

#define TILT_BLACK_PREFIX_LEN 20
#define TILT_IBEACON_MIN_LEN  25

static const uint8_t TILT_BLACK_PREFIX[TILT_BLACK_PREFIX_LEN] = {
	0x4C, 0x00, 0x02, 0x15,
	0xA4, 0x95, 0xBB, 0x30, 0xC5, 0xB1, 0x4B, 0x44,
	0xB5, 0x12, 0x13, 0x70, 0xF0, 0x2D, 0x74, 0xDE,
};

static inline bool tilt_black_decode(const uint8_t *mfg, uint8_t len,
				     int16_t *temp_centi_c,
				     uint16_t *gravity_x1000)
{
	if (mfg == NULL || len < TILT_IBEACON_MIN_LEN) {
		return false;
	}
	if (memcmp(mfg, TILT_BLACK_PREFIX, TILT_BLACK_PREFIX_LEN) != 0) {
		return false;
	}

	uint16_t temp_f      = ((uint16_t)mfg[20] << 8) | mfg[21];
	uint16_t gravity_x1k = ((uint16_t)mfg[22] << 8) | mfg[23];

	int32_t centi = ((int32_t)temp_f - 32) * 500 / 9;
	if (centi >  32767) centi =  32767;
	if (centi < -32768) centi = -32768;

	*temp_centi_c  = (int16_t)centi;
	*gravity_x1000 = gravity_x1k;
	return true;
}
